/* create table tablename(
        column_name_date_type(length),
        ....
        );

*/
drop TABLE EMP_DDL;
create TABLE EMP_DDL(
        EMPNO Number(4),
        ENAME VARCHAR2(10),
        JOB VARCHAR2(9),
        MGR NUMBER(4),
        HIREDATE DATE,
        SAL NUMBER(7,2),
        COMM NUMBER(7,2),
        DEPTNO NUMBER(2)
);
DESC EMP_DDL;
DROP TABLE DEPT_DDL;
CREATE TABLE DEPT_DDL
As SELECT * FROM DEPT;
DROP TABLE SALGRADE_DDL;
CREATE TABLE SALGRADE_DDL
as select * from SALGRADE;
DESC SALGRADE_DDL;

/*ALTER TABLE TABLE_NAME
    1.ADD COLNAME DATATYPE;
    2.DROP COLNAME;
    3.MODIFY COLNAME DATATYPE
    4.RENAME COLNAME OLD_COLNAME TO NEW_COLNAME
*/
ALTER TABLE SALGRADE_DDL
ADD PARTY VARCHAR2(20);

ALTER TABLE SALGRADE_DDL
RENAME COLUMN PARTY TO HOME;

ALTER TABLE SALGRADE_DDL
MODIFY HOME NUMBER(10);
DESC SALGRADE_DDL;

ALTER TABLE SALGRADE_DDL
DROP COLUMN HOME;
DESC SALGRADE_DDL;

RENAME SALGRADE_DDL TO SALZIP;
DESC SALZIP;
SELECT * FROM SALZIP;

TRUNCATE TABLE SALZIP;
DROP TABLE SALZIP;

/*
 CONSTRAINT
    NOT NULL / UNIQUE / PRIMARY KEY / FOREIGN KEY / CHECK / DEFAULT
    내부 데이터 제약조건 작성방법
*/
DROP TABLE PERSONS;
DROP TABLE PERSONS2;
CREATE TABLE PERSONS(
    ID VARCHAR2(4) PRIMARY KEY,
    NAME VARCHAR2(20) NOT NULL UNIQUE,
    AGE NUMBER(3) CHECK(AGE>=18),
    TELNUM VARCHAR2(20),
    ADDR VARCHAR2(100) DEFAULT 'SEOUL',
    BDAY DATE DEFAULT SYSDATE
);
INSERT INTO PERSONS(ID,NAME,AGE,TELNUM)
VALUES('1001','SCOTT',20,'010123445567');
INSERT INTO PERSONS(NAME,AGE,TELNUM)
VALUES('SCOTT',20,'010123445567');

CREATE TABLE PERSONS2(
    ID VARCHAR2(4),
    NAME VARCHAR2(20) NOT NULL,
    AGE NUMBER(3),
    TELNUM VARCHAR2(20),
    ADDR VARCHAR2(100) DEFAULT 'SEOUL',
    BDAY DATE DEFAULT SYSDATE,
    CONSTRAINT PK_PERSON2 PRIMARY KEY(ID),
    CONSTRAINT UN_PERSON2 UNIQUE(NAME),
    CONSTRAINT CHK_PERSON2 CHECK(AGE>=18)
);
/* 제약조건 변경, 삭제 */
ALTER TABLE PERSONS2 MODIFY ADDR DEFAULT 'PARIS';
ALTER TABLE PERSONS2 DROP CONSTRAINT CHK_PERSON2;
ALTER TABLE PERSONS2 ADD CONSTRAINT CHK_P2 CHECK(AGE>50);

DROP TABLE PLAYS;
CREATE TABLE PLAYS(
     PLAY_ID NUMBER(10) PRIMARY KEY,
     PLAY_RESOULT VARCHAR2(100),
     PERSONS_ID VARCHAR2(4),
     /* CASCADE를 사용하면 글 삭제시 댓글이 같이 지워지는것처럼 데이터가 처리 방법이 상속되어 같이 삭제함 */
     CONSTRAINT FK_PLAYS FOREIGN KEY(PERSINS_ID) REFERENCES PERSONS(ID) ON DELETE CASCADE
);
/* ON DELETE SET NULL (FOREIGN KEY)상속된 데이터를 삭제하지않고 NULL값으로 변경함 */

DROP TABLE PKTABLE;
DROP TABLE FKTABLE;
CREATE TABLE PKTABLE(
    PKVAL VARCHAR2(10),
    CONSTRAINT PK_KEY PRIMARY KEY(PKVAL)
);
CREATE TABLE FKTABLE(
    PKVAL VARCHAR2(10),
    FKVAL VARCHAR2(10)
);
ALTER TABLE FKTABLE ADD CONSTRAINT FK_KEY FOREIGN KEY(FKVAL) REFERENCES PKTABLE(PKVAL) ON DELETE CASCADE;
ALTER TABLE FKTABLE ADD CONSTRAINT FKT_PK_KEY PRIMARY KEY(PKVAL);

INSERT INTO PKTABLE VALUES('PK1');
INSERT INTO PKTABLE VALUES('PK2');
INSERT INTO PKTABLE VALUES('PK3');
SELECT * FROM PKTABLE;

INSERT INTO FKTABLE VALUES('PK1-VAL1','PK1');
INSERT INTO FKTABLE VALUES('PK1-VAL2','PK1');
INSERT INTO FKTABLE VALUES('PK2-VAL1','PK2');
INSERT INTO FKTABLE VALUES('PK2-VAL2','PK2');
INSERT INTO FKTABLE VALUES('PK3-VAL1','PK3');
INSERT INTO FKTABLE VALUES('PK3-VAL2','PK3');
SELECT * FROM FKTABLE;

DELETE FROM PKTABLE WHERE PKVAL='PK1';
SELECT * FROM PKTABLE;
SELECT * FROM FKTABLE;

CREATE TABLE EMP_HW(
    EMPNO NUMBER(4) NOT NULL,
    ENAME VARCHAR2(10),
    JOB VARCHAR2(9),
    MGR NUMBER(4),
    HIREDATE DATE,
    SAL NUMBER(7,2),
    COMN NUMBER(7,2),
    DEPTNO NUMBER(2),
    CONSTRAINT FK_DEPTNO2 FOREIGN KEY(DEPTNO) REFERENCES DEPT(DEPTNO),
    CONSTRAINT PK_EMP2 PRIMARY KEY(EMPNO)
);

/* Q2 EMP_HW 컬럼 BIGO 추가 VARCHAR2(20) */
ALTER TABLE EMP_HW ADD BIGO varchar(20);
DESC EMP_HW;
/* Q3 BIGO 컬럼 타입 VARCHAR2(40) */
ALTER TABLE EMP_HW
MODIFY BIGO varchar(20);
DESC EMP_HW;
/* Q4 BIGO 컬럼의 이름을 REMARK로 변경 */
ALTER TABLE EMP_HW
RENAME COLUMN BIGO TO REMARK;
DESC EMP_HW;
--Q5 삭제
DROP TABLE EMP_HW;
DESC EMP_HW;

